### ISSUE TITLE
Crash on incomplete class method

### ISSUE THREAD

**Issue by freemanoid** [AtomLinter/linter-reek#35]
I got this error on such file:

```ruby
class Create
  def self.

  end
end
```

>
Error: create.rb:6:1: error: unexpected token $end
>
create.rb: Parser::SyntaxError: unexpected token $end
Error: create.rb:6:1: error: unexpected token $end
create.rb: Parser::SyntaxError: unexpected token $end
    at parameters.exit (~/.atom/packages/linter-reek/node_modules/atom-linter/lib/helpers.js:131:25)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

linter-reek: "2.1.3"
atom-linter: "4.5.0"
executablePath: "~/.rvm/gems/ruby-2.1.2@global/wrappers/reek"
Mac OS 10.11.3

**Comment by troessner** [comment]
Interesting. This example causes `Reek` itself to crash when it actually shouldn't.
We'll look into [this](https://github.com/troessner/reek/issues/859)

**Comment by Arcanemagus** [comment]
Thanks for checking on this @troessner! Subscribed to the related issues.

**Comment by troessner** [comment]
Fixed in `parser` and updated [in Reek](https://github.com/troessner/reek/pull/861) as well - please use the latest `Reek` version and this problem should be gone.

**Comment by freemanoid** [comment]
`reek 3.10.2`
Still fails.

From console:
>
reek create.rb
create.rb:6:1: error: unexpected token $end
create.rb:6:
create.rb:6:
create.rb: Parser::SyntaxError: unexpected token $end

File as before:
```ruby
class Create
  def self.

  end
end
```

**Comment by troessner** [comment]
Well, it's ok that it fails in general since it is invalid syntax. As you can see [here](https://github.com/troessner/reek/blob/master/lib/reek/source/source_code.rb#L84) we're rescuing Parser::SyntaxError. This means `Reek` will just skip this file.  Before the fix `Reek` itself would crash, which now doesn't happen anymore as you can see in the output above.

Which means in turn that `linter-reek` should work as expected for you ;)

**Comment by dhagerty9009** [comment]
I just created a similar method in a Ruby file, and as far as I can tell the linter behaved as expected. It rescued from the syntax error, and on fixing the syntax error everything continued to work normally.

I'm closing the issue as there is no longer any unexpected behavior.

**Comment by gerrywastaken** [comment]
@dhagerty9009 So I just upgraded reek to the latest and made sure linter-reek was also at the latest. Every time I enter a character I get a new one of those error boxes popping up at the right had side as I'm editing a file:

<img width="1471" alt="screen shot 2016-08-20 at 4 31 41 pm" src="https://cloud.githubusercontent.com/assets/71481/17829498/010577c6-66f4-11e6-83aa-c8b0e3afe647.png">

It seems you are saying this is expected? Or am I getting different results from others?

**Comment by dhagerty9009** [comment]
I'm not sure where the issue is. If you are leaving the method looking like the sample provided, that is invalid syntax and it should produce errors. If you are turning `self.` into `self.something`, then the error should disappear as that is valid syntax.

**Comment by gerrywastaken** [comment]
@dhagerty9009 

> If you are turning self. into self.something, then the error should disappear as that is valid syntax.

It doesn't, I have to close them. It's also very distracting and can end up covering up code. On some longer lines it can even end up covering the code I'm trying to fix. These dialog boxes seem like they were never intended to be used as linter-reek is using them. They should be rare not something that appears during the course of writing code. I've never seen another plugin use them in this way, but your prerogative I guess.

**Comment by gerrywastaken** [comment]
@dhagerty9009 https://github.com/atom/atom/issues/8152#issuecomment-266265451
